name: docs

on:
  workflow_dispatch:

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: docs
        run: curl -X POST -d token=${{ secrets.RTD_API_TOKEN }} https://readthedocs.org/api/v2/webhook/glnext-compiler/148637/
